# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"npmaxabs": "00_core.ipynb",
         "simulated_shares": "00_core.ipynb",
         "simulated_mean_shares": "00_core.ipynb",
         "berry_core": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://bsalanie.github.io/cython_berry_core/"

git_url = "https://github.com/bsalanie/cython_berry_core/tree/masters/"

def custom_doc_links(name): return None
